dataFileName: 'pattern.yml'
patternlab:
  dest: './patternlab'
  version: '0.6.6'
globalAssets: './global-assets'
githubrepo: scottnath-pattern-library
npmPatternRepos:
  -
    name: 'base'
    repoDir: 'pattern-library'
templates:
  -
    name: 'site-sass'
    src: './lib/templates/style.scss'
    destDir: './patternlab/source/css/scss'
    destFile: 'style.scss'
  -
    name: 'site-head'
    src: './lib/templates/head.twig'
    destDir: './patternlab/source/_meta'
    destFile: '_00-head.twig'
  -
    name: 'site-foot'
    src: './lib/templates/foot.twig'
    destDir: './patternlab/source/_meta'
    destFile: '_01-foot.twig'
fileTypes:
  css:
    globalAssetsSrc:
      - '{{ globalAssets }}/styles/css/**/*.css'
    globalAssetsDest: '{{ patternlab.dest }}/source/css/global-assets'
  fonts:
    globalAssetsSrc:
      - '{{ globalAssets }}/fonts/*'
      - '{{ globalAssets }}/fonts/**/*'
    globalAssetsDest: '{{ patternlab.dest }}/source/fonts'
  images:
    globalAssetsSrc:
      - '{{ globalAssets }}/images/*'
      - '{{ globalAssets }}/images/**/*'
    globalAssetsDest: '{{ patternlab.dest }}/source/images'
  js:
    prototyperSrcDir: '{{ patternlab.dest }}/source/js'
    globalAssetsSrc:
      - '{{ globalAssets }}/js/**/*.js'
  patterns:
    prototyperDestDir: '{{ patternlab.dest }}/source/_patterns'
  sass:
    prototyperSrcDir: '{{ patternlab.dest }}/source/css/scss'
    prototyperSrc: '{{ patternlab.dest }}/source/css/scss/style.scss'
    prototyperDestDir: '{{ patternlab.dest }}/source/css'
    prototyperDest: '{{ patternlab.dest }}/source/css/style.css'
    globalAssetsSrc:
      - '{{ globalAssets }}/styles/scss/**/*.scss'
    globalAssetsDest: '{{ patternlab.dest }}/source/css/scss/global-assets'
gulpTasks:
  fileGlobInject:
    js:
      srcFile: '{{ patternlab.dest }}/source/_meta/_01-foot.twig'
      destDir: '{{ patternlab.dest }}/source/_meta'
    sass:
      srcFile: '{{ fileTypes.sass.prototyperSrc }}'
      destDir: '{{ fileTypes.sass.prototyperSrcDir }}'
  gulpSass:
    dependencies:
      - 'glob-inject-sass-all'
  patternImporter:
    localPatterns:
      config:
        htmlTemplateDest: '{{ fileTypes.patterns.prototyperDestDir }}'
        stylesDest: '{{ fileTypes.sass.prototyperSrcDir }}/local'
        scriptsDest: '{{ fileTypes.js.prototyperSrcDir }}/local'
        convertCategoryTitles: false
      taskName: 'patterns-import-local'
      src:
        - './patterns/**/pattern.yml'
  replaceUrl:
    ghPagesPrefix: '/{{ githubrepo }}'
    src:
      - '{{ patternlab.dest }}/source/**/*.json'
